# Generated by Django 4.2 on 2024-09-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_amount',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='discount amount'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Percentage'), (2, 'Constant')], default=2, null=True, verbose_name='discount type'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_discount',
            field=models.BooleanField(default=False, verbose_name='has discount'),
        ),
    ]
