# Generated by Django 4.2 on 2024-09-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_discount_amount_product_discount_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='discount amount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Percentage'), (2, 'Constant')], default=2, verbose_name='discount type'),
        ),
    ]
