version: '3.8'

services:
  postgres:
    image: postgres
    container_name: ecommerce_postgres
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: 123456
       POSTGRES_DB : ecommerce
       PG_DATA: /data/postgres
    volumes:
      - postgres:/data/postgres 
    ports:
      - "5432:5432"
    networks:
      - ecommerce_network
    restart: unless-stopped
  
  pgadmin4:
    image: dpage/pgadmin4
    container_name: ecommerce_pgadmin
    environment:
       PGADMIN_DEFAULT_EMAIL: alex.apple2403@gmail.com
       PGADMIN_DEFAULT_PASSWORD: 123456
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "8090:80"
    networks:
      - ecommerce_network
    restart: unless-stopped
    depends_on: 
    - postgres
  
  redis:
    image: redis
    container_name: ecommerce_redis
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - redis:/etc/redis.conf
      - redis:/data
    ports:
      - "6379:6379"
    networks:
      - ecommerce_network
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:
  redis:
  logs:

networks:
  ecommerce_network:
   driver: bridge